### PR TITLE
Update long strings in German translation

### PR DESCRIPTION
**Pull request by WebSnke**

### CODE REVIEW

**Comment by WebSnke** [comment]
What is the difference between a "Save Card", "MemCard" and "SD Card"?

**Comment by WebSnke** [comment]
I also noticed that "ä", "ö" and "ü" are not displayed properly. I could write "ae", "oe" and "ue" instead but that would make the strings even longer.

**Comment by eku** [comment]
> I could write "ae", "oe" and "ue"

Please don't.

Let's check proper encoding of the Umlauts. Are they UTF-8? Does the output handle UTF-8?

**Comment by WebSnke** [comment]
> > I could write "ae", "oe" and "ue"
> 
> Please don't.
> 
> Let's check proper encoding of the Umlauts. Are they UTF-8? Does the output handle UTF-8?
> 
> 

Yeah, Umlaute are included in UTF-8.

**Comment by xjsxjs197** [comment]
Let me check. It could also be a problem with the German font that was used.

**Comment by xjsxjs197** [comment]
I have fixed the code logic, and special characters can now be displayed correctly. You can use this version to test, but please note that the translations inside are still from the previous version.

[De.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13172946/De.zip)

[WiiSXRX_Release.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13172949/WiiSXRX_Release.zip)

**Comment by WebSnke** [comment]
> I also noticed that "ä", "ö" and "ü" are not displayed properly. I could write "ae", "oe" and "ue" instead but that would make the strings even longer.

@xjsxjs197 
So, what's the difference?

**Comment by xjsxjs197** [comment]
> > I also noticed that "ä", "ö" and "ü" are not displayed properly. I could write "ae", "oe" and "ue" instead but that would make the strings even longer.
> 
> @xjsxjs197 So, what's the difference?

"ä", "ö" and "ü" can displayed properly.

**Comment by WebSnke** [comment]
> > > I also noticed that "ä", "ö" and "ü" are not displayed properly. I could write "ae", "oe" and "ue" instead but that would make the strings even longer.
> > 
> > 
> > @xjsxjs197 So, what's the difference?
> 
> "ä", "ö" and "ü" can displayed properly.

Oh, sorry. I meant the difference "Save Card", "MemCard" and "SD Card".

**Comment by xjsxjs197** [comment]
> Oh, sorry. I meant the difference "Save Card", "MemCard" and "SD Card".
It should be used in different locations, please refer to the screenshot below
In addition, a new version of the font library has been created

image

[De.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13183988/De.zip)

**Comment by WebSnke** [comment]
Ok, thanks. But what exactly does "Memcard save device" and "Save States Device do?

**Comment by eku** [comment]
> Ok, thanks. But what exactly does "Memcard save device" and "Save States Device do?

Well, WiiStation uses files as virtual memcards. Theses files can be stored either on SD card or USB devices connected to your Wii.

**Comment by WebSnke** [comment]
> > Ok, thanks. But what exactly does "Memcard save device" and "Save States Device do?
> 
> Well, WiiStation uses files as virtual memcards. Theses files can be stored either on SD card or USB devices connected to your Wii.

What translation would you suggest?

**Pull request merged**
