### PR TITLE
Add basic CHD (v1-v5) support via libchdr. (aliaspider, notaz, others)

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
After scratching my head and investigating and studying a bit the code of [libchdr](https://github.com/rtissera/libchdr) and [PCSX-ReARMed](https://github.com/libretro/pcsx_rearmed), i finally achieved one of my (and the community's) goals of the PS1 emulators for Wii: having a nice and neat CHD compressed format support.

This PR adds said CHD support, a compressed file format used originally by MAME but it's now present in various emulators, including PCSX-ReARMed.

Tested various CHD files of PS1 games and it's 100% working, including CDDA audio.

Tested:
- CTR: Crash Team Racing
- Pepsiman
- Vib-Ribbon
- Hot Wheels: Turbo Racing
- The Pink Panther: Pinkiadelic Pursuit
- Street Fighter EX2

### CODE REVIEW

**Comment by saulfabregwiivc** [comment]
Closing this PR temporally cause it broke CDDA support for BIN/CUE and other formats.
Trying hard for fix them :P

**Comment by saulfabregwiivc** [comment]
Closing this PR temporally cause it broke CDDA support for BIN/CUE and other formats.
Trying hard for fix them :P

**Comment by saulfabregwiivc** [comment]
After some further investigation, a little part of the code was wrong (specifically the cddaBigEndian part for loading CHDs).
I corrected that, and i reverted a commit which caused more issues with CDDA audio.

Now CDDA audio is working now on both CHDs and BIN/CUEs (and other supported formats).

This can be merged. :3

**Comment by saulfabregwiivc** [comment]
After several testings, this CHD support is now working as intended.

This can be merged. :)
Or should i make another PR with fewer commits?

**Comment by xjsxjs197** [comment]
Thank you very much for your hard work. The PS emulators on Wii are getting better and better now(^_^).
I hope this feature will not have a significant impact on the remaining memory, as in the case of the lightrec core, only about 2M of memory is left. Merge to the main branch first. 

Recently, I have been too busy with work here, and I have spent less time and energy on this project.
One feature that I am more concerned about now is the support of the Hid Controller. I also studied nintendont code for a period of time. And wrote some code in the HidController branch. Obviously, it didn't run as planned. Although I sent a help email to Fix94, I did not receive a reply.
If you have interest and time there, you can also study the support of HidController together.

Thank you very much.

**Pull request merged**
