### PR TITLE
finish migrating properly from libOGC to libOGC2

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
Info: https://github.com/extremscorner/libogc2#readme

I saw you're now migrating from official libOGC to @Extrems' libOGC2, but Extrems states that you can migrate safely from libOGC to libOGC2 without having to delete your original libOGC, by just changing the locations of the rules on the Makefiles.

For use libOGC2, just download the latest artifacts from https://github.com/extremscorner/libogc2/actions , then extract its contents into the **C:/devkitPro/libogc2/** folder.

### CODE REVIEW

**Comment by saulfabregwiivc** [comment]
PR temporally closed, it's not compiling properly. I'll try your file.

**Comment by saulfabregwiivc** [comment]
Results of trying to compile with latest libOGC2:

without [my changes](https://github.com/xjsxjs197/WiiSXRX_2022/pull/89/files) = error while compiling on PadWiiSX.c

with [my changes](https://github.com/xjsxjs197/WiiSXRX_2022/pull/89/files) = error when linking because of undefined variables, as shown:

```
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:\Users\ASUS\AppData\Local\Temp\ccTT7lFW.ltrans10.ltrans.o: in function `_Z12LoadLanguagev.isra.0':
C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:216: undefined reference to `en_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:216: undefined reference to `en_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:223: undefined reference to `zh_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:223: undefined reference to `zh_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:224: undefined reference to `Kr_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:224: undefined reference to `Kr_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:219: undefined reference to `es_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:219: undefined reference to `es_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:225: undefined reference to `pt_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:225: undefined reference to `pt_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:226: undefined reference to `it_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/gui2/gettext.cpp:226: undefined reference to `it_lang_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:\Users\ASUS\AppData\Local\Temp\ccTT7lFW.ltrans10.ltrans.o: in function `_ZN4menu7IplFontC2Ev.constprop.0':
C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/IPLFont.cpp:84: undefined reference to `En_dat_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/12.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/IPLFont.cpp:85: undefined reference to `En_dat_size'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/opt/devkitpro/libogc2/wii_rules:30: /c/ustealthmods/WiiStationmain09052023/Gamecube/WiiSXRX_Release.elf] Error 1
make[1]: *** [Makefile_Wii_Release:120: build_release] Error 2
make[1]: Leaving directory '/c/ustealthmods/WiiStationmain09052023/Gamecube'
make: *** [Makefile:27: Wii_Release] Error 2
```
Could you try to fix these errors please?
I will reopen the PR.

**Comment by saulfabregwiivc** [comment]
also, i'm compiling with latest devkitPPC. (i'm using r41-2)

**Comment by Extrems** [comment]
That's an interesting definition of latest when libogc2 itself mentions r43.

**Comment by saulfabregwiivc** [comment]
> That's an interesting definition of latest when libogc2 itself mentions r43.

Nice catch, @Extrems. I was using a quite old devkitPPC, i'll try updating it.

**Comment by saulfabregwiivc** [comment]
nope, still errors.
This time throws me:

```
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld.exe: C:\Users\ASUS\AppData\Local\Temp\ccwZTFF7.ltrans10.ltrans.o: in function `_ZN4menu7IplFontC2Ev.constprop.0':
C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/IPLFont.cpp:84: undefined reference to `En_dat_size'
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/ustealthmods/WiiStationmain09052023/Gamecube/libgui/IPLFont.cpp:85: undefined reference to `En_dat_size'
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld.exe: C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/lib\libsysbase.a(libsysbase_libsysbase_a-sbrk.o): in function `_sbrk_r':
(.text._sbrk_r+0x6e): undefined reference to `__end__'
C:/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld.exe: (.text._sbrk_r+0x72): undefined reference to `__end__'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/opt/devkitpro/libogc2/wii_rules:30: /c/ustealthmods/WiiStationmain09052023/Gamecube/WiiSXRX_Release.elf] Error 1
make[1]: *** [Makefile_Wii_Release:120: build_release] Error 2
make[1]: Leaving directory '/c/ustealthmods/WiiStationmain09052023/Gamecube'
make: *** [Makefile:27: Wii_Release] Error 2
```

I suspect it's related to the filelist outdated code and also outdated code on IPLFont.cpp.
Any suggestions for update the code for be compiled on latest devkitPPC?

**Comment by xjsxjs197** [comment]
Sorry, I used the old base_rules for the compilation of the dat.
image

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 Thanks for the info.
i modified base_rules on my devkitPPC, and it worked fine.
DISCLAIMER: please use devkitPPC r41-2 for compile this now, the newer one (r43-3) looks like had a regression and won't let me compile :P 
I will add that info later.

**Comment by Extrems** [comment]
It's not a regression. Your copy of libogc2 is simply too old to be compatible.

There's a reason why the installation and update instructions are what they are.

**Comment by saulfabregwiivc** [comment]
> It's not a regression. Your copy of libogc2 is simply too old to be compatible.
> 
> There's a reason why the installation and update instructions are what they are.

Thanks for your quick reply.
This time after re-updating to devkitPPC r43-3, i installed libogc2 like you mentioned on the README.
Also, i have noticed something why my dol wasn't working: (sorry for my stupidity) - i recompiled the emulator with "my changes" for try to fix the linking issues, but looks like it's not needed anymore...
I recloned WiiStation code and recompiled it, and now works ;)

Thanks @Extrems and @xjsxjs197 :)

**Comment by saulfabregwiivc** [comment]
Ok... the dol can be loaded fine, but now i'm having this problem now (maybe related to SD card code on libOGC2, or WiiStation?

Trying to load a game from SD throws me ISI exception.
Trying to load from DVD just freezes the console
All else works fine :P 

image

What's going on now?

**Comment by xjsxjs197** [comment]
The version that I can compile correctly at the moment is devkitPPC41-2, libogc2(Apr 12, 2023 7456c4abf3e8e8ccd7eac7bb7cbe808128befa55), lightning2.2.1 and latest lightrec.
The following is the version I have compiled:
https://github.com/xjsxjs197/WiiSXRX_2022/raw/main/lightrec+Libogc2.zip

Using the latest versions of devkitPPC43 and libogc2, the same problem indeed occurs, and I'm not sure about the specific reason either.

**Pull request merged**
