### PR TITLE
Various updates merge from upstream CDROM, SPU, DFSound from PCSX-ReARMed - 04/11/2023

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
Fixes various things on **Dino Crisis**, **Blue's Clues: Blue's Big Musical**, **FIFA 99**, and **Star Wars: Episode I - The Phantom Menace**.
Tests by the community also confirms it also fixes **Vib-Ribbon** (in Lightrec), **Oddworld: Abe's Oddysee**, **Darkstalkers 3**, **Grand Theft Auto 2**, **Rollcage**, **KISS Pinball**, etc.

Also updates Lightrec until git https://github.com/pcercuei/lightrec/commit/b9e4089b3b6121f2077dc85a8fe7f934e3ae1c20.

### CODE REVIEW

**Comment by saulfabregwiivc** [comment]
As mentioned in comment 1, these changes makes WiiStation to be very similar in code to PCSX-ReARMed, which means even more compatibility.
This can be merged. :)

**Comment by xjsxjs197** [comment]
Regarding the compilation of Lightrec, I have two questions to ask.
1: Currently, the output level of Log in the compiled libLightrecWithLog.a is set to "debug", resulting in too much output information. Is it possible to compile one with an "Info" level?

2: I have already merged the code of Lightrec into the main branch, but when I compile it in my environment, the Lightrec has issues, and it gives errors directly in HLE mode. However, when I use your compiled version, it works fine. Could you please provide me with the environment information for your Lightrec compilation, such as the devkitPPC version and various parameter details in the Makefile?

**Comment by saulfabregwiivc** [comment]
> 1: Currently, the output level of Log in the compiled libLightrecWithLog.a is set to "debug", resulting in too much output information. Is it possible to compile one with an "Info" level?

Correct.
@pcercuei explained this in my question for add Lightrec to WiiStation:

> In this command:
> `cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= ..`
> You can pass (use) the additional command -DLOG_LEVEL=Info to cmake to only display info and other things of Lightrec.
> So it would be:
> `cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= .. -DLOG_LEVEL=Info`



> 2: I have already merged the code of Lightrec into the main branch, but when I compile it in my environment, the Lightrec has issues, and it gives errors directly in HLE mode. However, when I use your compiled version, it works fine. Could you please provide me with the environment information for your Lightrec compilation, such as the devkitPPC version and various parameter details in the Makefile?

I use **devkitPPC r41-2** (which is mentioned in the README.md) (you can get here at https://wii.leseratte10.de/devkitPro/devkitPPC/r41%20%282022-05-31%29) and the libOGC2/Lightrec library which is included here https://github.com/xjsxjs197/WiiSXRX_2022/raw/main/lightrec%2BLibogc2.zip

Remember that in the portlibs (specifically in the folder **devkitPro/portlibs/wii/lib/** you also have to use the custom libSDL.a which you made. https://github.com/xjsxjs197/WiiSXRX_2022/raw/main/libSDL.a

Don't know if i'm clear with this info, but hope this helps.

**Comment by xjsxjs197** [comment]
Thank you very much! Since I didn't use cmake and directly created a Makefile, it's possible that the values defined in lightrec-config.h are causing the issue.
Changing HAS_DEFAULT_ELM to 1 resolved the issue and now it runs correctly.
But the version I compiled is hundreds of kilobytes larger than yours, and other values may also have an impact.

**Pull request merged**
