### PR TITLE
Fix MediEvil PAL and other large video resolution games (emukidid, pcercuei)

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
Reference: https://github.com/emukidid/pcsxgc/commit/9f1d5ae4bf38ded679acecd5b4db39fce91d0829

### CODE REVIEW

**Comment by Jokippo** [comment]
I think this was already fixed here:
[https://github.com/Jokippo/WiiSXRX_2022240p/commit/c6ac96070ef1981b4b36af204aa458f11a4cd1f2](url)
Or are there some games that benefit from an even bigger buffer?

**Comment by saulfabregwiivc** [comment]
@Jokippo i suppose so.

Btw, is there any chance to backport ICache emulation on Lightrec from PCSX-ReARMed?

There are games that depend of it for run correctly (Studio 33 F1 games, Xenogears, EA Sports F1 games).

**Comment by Jokippo** [comment]
@saulfabregwiivc Do you mean it does fix more games? Which games have you tested that don't work with the https://github.com/Jokippo/WiiSXRX_2022240p/commit/c6ac96070ef1981b4b36af204aa458f11a4cd1f2 fix alone?

**Comment by saulfabregwiivc** [comment]
@Jokippo OK, after i tested some PAL and other high res games, looks like this PR (by me) is somewhat similar to yours, with the same results (games running adequately with your fix).

Closing this one.

(But what about ICache implementation on Lightrec for WiiStation?)

**Pull request closed without merging**
